// ─────────────────────────────────────────
// Duggirala
// German Daily Learning System
// ─────────────────────────────────────────

const {
  Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow,
  TableCell, AlignmentType, WidthType,
} = require("docx");
const fs = require("fs");

const PAGE_W = 12240;
const PAGE_H = 15840;
const MARGIN = 1440;

function h1(text) {
  return new Paragraph({ text, heading: HeadingLevel.HEADING_1, spacing: { before: 300, after: 120 } });
}
function h2(text) {
  return new Paragraph({ text, heading: HeadingLevel.HEADING_2, spacing: { before: 200, after: 80 } });
}
function p(text) {
  return new Paragraph({ children: [new TextRun({ text, font: "Arial", size: 18 })], spacing: { after: 80 } });
}
function bullet(text) {
  return new Paragraph({ children: [new TextRun({ text, font: "Arial", size: 18 })], bullet: { level: 0 }, spacing: { after: 60 } });
}
function bold(text) {
  return new Paragraph({ children: [new TextRun({ text, font: "Arial", size: 18, bold: true })], spacing: { after: 60 } });
}

function tbl(headers, rows) {
  const colW = Math.floor((PAGE_W - 2 * MARGIN) / headers.length);
  const makeCell = (text, isHeader = false) => new TableCell({
    children: [new Paragraph({ children: [new TextRun({ text: String(text), font: "Arial", size: 16, bold: isHeader })] })],
    width: { size: colW, type: WidthType.DXA },
  });
  return new Table({
    width: { size: PAGE_W - 2 * MARGIN, type: WidthType.DXA },
    rows: [
      new TableRow({ children: headers.map(h => makeCell(h, true)), tableHeader: true }),
      ...rows.map(row => new TableRow({ children: row.map(c => makeCell(c)) })),
    ],
  });
}

// ── Cover ──────────────────────────────────────────────────────────────────────
const cover = [
  new Paragraph({ children: [new TextRun({ text: "DeutschTaeglich — SaaS Roadmap", font: "Arial", size: 52, bold: true })], alignment: AlignmentType.CENTER, spacing: { before: 2000, after: 400 } }),
  new Paragraph({ children: [new TextRun({ text: "Technical Reference for Claude Code", font: "Arial", size: 26, italics: true })], alignment: AlignmentType.CENTER, spacing: { after: 200 } }),
  p("German learning automation platform. 20 words/day x 125 weekdays = 2,500 words (A1->B1). Scales from single GitHub Actions cron to multi-tenant SaaS."),
];

// ── S1: Architecture ───────────────────────────────────────────────────────────
const s1 = [
  h1("1. Architecture"),
  h2("1.1 Current (Single-user, GitHub Actions)"),
  tbl(["Component","Choice","Why"],
    [
      ["Scheduler","GitHub Actions dual-cron","Free, no infra"],
      ["AI","Gemini 1.5 Flash","Free tier: 1,500 req/day; 1M context"],
      ["PDF","fpdf2 (Python)","Pure Python, no dependencies, A4 OK"],
      ["Email","Gmail SMTP port 587","Free with app password"],
      ["State","progress.json + last_sent_words.json","Git-committed, zero infra"],
    ]
  ),
  h2("1.2 SaaS Target Architecture"),
  tbl(["Layer","Technology","Notes"],
    [
      ["Frontend","Next.js 14 (App Router) + Tailwind","Dashboard + marketing site"],
      ["API","Next.js Route Handlers (REST)","Same repo, Vercel deploy"],
      ["Auth","Supabase Auth (JWT)","Email/password + OAuth"],
      ["Database","Supabase (Postgres)","Row-level security per user"],
      ["Job Queue","Trigger.dev (self-hosted or cloud)","Per-user cron scheduling"],
      ["File Storage","Cloudflare R2","PDFs, cheap egress"],
      ["Payments","Stripe Checkout + Customer Portal","Subscriptions + webhooks"],
      ["Email (scale)","SendGrid or Mailgun","Delivery tracking, bounce handling"],
      ["Monitoring","Sentry + Uptime Robot","Error tracking + uptime"],
      ["Cache","Supabase + Redis (optional)","AI content cache per word"],
    ]
  ),
  h2("1.3 Data Flow"),
  bullet("Trigger.dev fires per-user job at scheduled time in user timezone"),
  bullet("Job calls Gemini API: 1 batched call -> JSON array of 20 word objects"),
  bullet("Cache check: if word was generated before, use cached JSON (saves Gemini tokens)"),
  bullet("Build PDF in memory with fpdf2 or reportlab"),
  bullet("Upload PDF to R2, store signed URL in Supabase"),
  bullet("Send email via SendGrid with PDF attached"),
  bullet("Update user progress row in Supabase"),
  bullet("Emit lesson.sent webhook event"),
];

// ── S2: Database Schema ────────────────────────────────────────────────────────
const s2 = [
  h1("2. Database Schema"),
  h2("users"),
  tbl(["Column","Type","Notes"],
    [
      ["id","uuid PK","Supabase auth.users FK"],
      ["email","text UNIQUE",""],
      ["name","text",""],
      ["plan","text","free|pro|enterprise"],
      ["timezone","text","e.g. Europe/Berlin"],
      ["delivery_time","time","e.g. 07:00"],
      ["created_at","timestamptz",""],
      ["stripe_customer_id","text","nullable"],
    ]
  ),
  new Paragraph({ spacing: { after: 120 } }),
  h2("progress"),
  tbl(["Column","Type","Notes"],
    [
      ["id","uuid PK",""],
      ["user_id","uuid FK -> users",""],
      ["next_word_index","int","0-2499"],
      ["next_video_index","int","0-129"],
      ["days_completed","int","0-125"],
      ["total_words_sent","int","0-2500"],
      ["last_sent_date","date","ISO date, dedup guard"],
      ["streak_days","int","consecutive weekdays"],
      ["completed","bool","true when days_completed=125"],
    ]
  ),
  new Paragraph({ spacing: { after: 120 } }),
  h2("lessons"),
  tbl(["Column","Type","Notes"],
    [
      ["id","uuid PK",""],
      ["user_id","uuid FK",""],
      ["day_number","int","1-125"],
      ["level","text","A1|A2|B1"],
      ["words","jsonb","array of 20 word objects from Gemini"],
      ["video_url","text","YouTube URL"],
      ["pro_tip","text","one of 125 tips"],
      ["pdf_url","text","R2 signed URL"],
      ["sent_at","timestamptz","null if pending"],
      ["email_message_id","text","for delivery tracking"],
    ]
  ),
  new Paragraph({ spacing: { after: 120 } }),
  h2("subscriptions"),
  tbl(["Column","Type","Notes"],
    [
      ["id","uuid PK",""],
      ["user_id","uuid FK",""],
      ["stripe_subscription_id","text",""],
      ["plan","text","free|pro|enterprise"],
      ["status","text","active|canceled|past_due|trialing"],
      ["current_period_end","timestamptz",""],
      ["cancel_at_period_end","bool",""],
    ]
  ),
  new Paragraph({ spacing: { after: 120 } }),
  h2("word_cache"),
  tbl(["Column","Type","Notes"],
    [
      ["word","text PK","German word"],
      ["level","text","A1|A2|B1"],
      ["data","jsonb","full Gemini-generated word object"],
      ["created_at","timestamptz",""],
    ]
  ),
];

// ── S3: API Endpoints ──────────────────────────────────────────────────────────
const s3 = [
  h1("3. API Endpoints"),
  h2("Auth"),
  tbl(["Method","Path","Auth","Notes"],
    [
      ["POST","/auth/register","No","body: {email,password,name,timezone}"],
      ["POST","/auth/login","No","returns access_token + refresh_token"],
      ["POST","/auth/refresh","No","rotate refresh token"],
      ["POST","/auth/logout","Bearer","revoke tokens"],
      ["GET","/auth/me","Bearer","current user profile"],
      ["POST","/auth/forgot-password","No","sends reset email"],
      ["POST","/auth/reset-password","No","body: {token,new_password}"],
    ]
  ),
  new Paragraph({ spacing: { after: 120 } }),
  h2("Lessons & Progress"),
  tbl(["Method","Path","Auth","Notes"],
    [
      ["GET","/lessons/today","Bearer","today's metadata: status, pdf_url"],
      ["GET","/lessons/:day","Bearer","full lesson with words array"],
      ["GET","/lessons","Bearer","paginated list, ?status=sent|pending"],
      ["POST","/lessons/:day/resend","Bearer","rate limited: 1/hr per lesson"],
      ["GET","/lessons/:day/pdf","Bearer","binary PDF or signed R2 URL redirect"],
      ["GET","/progress","Bearer","current_day, streak, completion_pct"],
      ["GET","/progress/stats","Bearer","words by category, projected completion"],
      ["POST","/progress/checkin","Bearer","mark lesson reviewed, update streak"],
    ]
  ),
  new Paragraph({ spacing: { after: 120 } }),
  h2("Subscriptions"),
  tbl(["Method","Path","Auth","Notes"],
    [
      ["GET","/subscription","Bearer","plan, status, period_end"],
      ["POST","/subscription/checkout","Bearer","body: {plan,billing_cycle} -> {checkout_url}"],
      ["POST","/subscription/portal","Bearer","Stripe self-service portal URL"],
      ["POST","/subscription/cancel","Bearer","cancel at period end"],
      ["GET","/subscription/invoices","Bearer","billing history"],
      ["POST","/webhooks/stripe","Stripe-Sig","HMAC verified, handles payment events"],
    ]
  ),
  new Paragraph({ spacing: { after: 120 } }),
  h2("Preferences & Schedule"),
  tbl(["Method","Path","Auth","Notes"],
    [
      ["GET","/preferences","Bearer","timezone, delivery_time, notification settings"],
      ["PUT","/preferences","Bearer","partial update, re-schedules Trigger.dev job"],
      ["GET","/schedule","Bearer","next 30 days of scheduled lessons"],
      ["POST","/schedule/pause","Bearer","body: {from,to}, max 30 days/quarter"],
      ["POST","/schedule/resume","Bearer","resume early"],
    ]
  ),
  new Paragraph({ spacing: { after: 120 } }),
  h2("Admin (role=admin required)"),
  tbl(["Method","Path","Notes"],
    [
      ["GET","/admin/users","list + search, paginated"],
      ["GET","/admin/users/:id","full profile + billing + lesson history"],
      ["POST","/admin/users/:id/override-plan","comps/support overrides, audit logged"],
      ["GET","/admin/metrics","DAU, MRR, ARR, churn, completion rate"],
      ["GET","/admin/lessons/queue","pending/failed Trigger.dev jobs"],
      ["POST","/admin/lessons/requeue","retry failed jobs"],
      ["GET","/admin/errors","recent error log with severity filter"],
    ]
  ),
];

// ── S4: Pricing ────────────────────────────────────────────────────────────────
const s4 = [
  h1("4. Pricing Tiers"),
  tbl(["Feature","Free","Pro (EUR 9.99/mo)","Enterprise (EUR 299/mo)"],
    [
      ["Days included","7","125 (full course)","125 per seat"],
      ["Words","140","2,500","2,500 per seat"],
      ["PDF access","Days 1-7 only","All 125 days","All days"],
      ["PDF download","No","Yes","Yes"],
      ["Streak tracking","No","Yes","Yes"],
      ["Completion cert","No","Yes","Yes"],
      ["Custom schedule","No","Yes","Yes"],
      ["Streak grace days","0","1/month","3/month"],
      ["Seats","1","1","Custom"],
      ["SSO","No","No","Yes"],
      ["Custom word lists","No","No","Yes"],
      ["SLA","None","None","99.9% + 4h support"],
      ["Annual discount","N/A","EUR 99/yr (2mo free)","EUR 2,990/yr"],
    ]
  ),
  new Paragraph({ spacing: { after: 120 } }),
  h2("Financial Targets"),
  tbl(["Phase","Timeline","MRR","Key Milestone"],
    [
      ["Launch","Month 1-3","EUR 500","50 Pro, product-market fit"],
      ["Growth","Month 4-6","EUR 4,500","300 Pro, 5 Enterprise, Product Hunt"],
      ["Scale","Month 7-12","EUR 22,500","1,500 Pro, 25 Enterprise"],
      ["Year 2","Month 13-24","EUR 130,000","10k Pro, 100 Enterprise"],
    ]
  ),
];

// ── S5: Frontend Pages ─────────────────────────────────────────────────────────
const s5 = [
  h1("5. Frontend Pages"),
  tbl(["Route","Page","Key Components"],
    [
      ["/","Marketing landing","Hero, pricing table, testimonials, CTA"],
      ["/auth/register","Sign up","Email/pass form, timezone picker, email verification"],
      ["/auth/login","Log in","Email/pass, forgot password link"],
      ["/dashboard","User dashboard","Progress ring, streak calendar, today's lesson card"],
      ["/lessons","Lesson history","Paginated list, search, PDF download"],
      ["/lessons/[day]","Single lesson","Word cards, summary table, video embed"],
      ["/settings","Preferences","Timezone, delivery time, notifications, danger zone"],
      ["/billing","Billing","Plan badge, upgrade button, invoice table"],
      ["/admin","Admin panel","User table, metrics cards, queue view"],
      ["/admin/users/[id]","User detail","Full profile, plan override, manual trigger"],
    ]
  ),
  new Paragraph({ spacing: { after: 120 } }),
  h2("Dashboard Component Specs"),
  bullet("Progress ring: SVG circle, current_day/125, color by level (blue A1, green A2, orange B1)"),
  bullet("Streak calendar: 125-day grid, GitHub contribution-graph style, filled=sent, empty=pending/skipped"),
  bullet("Today's lesson card: level badge, 20-word count, CTA to open lesson, status chip"),
  bullet("Words table in /lessons/[day]: word | article | meaning | level — sortable, searchable"),
];

// ── S6: Development Stack ──────────────────────────────────────────────────────
const s6 = [
  h1("6. Development Stack"),
  tbl(["Concern","Tool","Config Note"],
    [
      ["Framework","Next.js 14 App Router","src/ directory, TypeScript strict"],
      ["Styling","Tailwind CSS 3","tailwind.config.ts, no CSS modules"],
      ["State","Zustand (client) + SWR (server)","avoid Redux overhead"],
      ["Forms","React Hook Form + Zod","schema validation on client + server"],
      ["DB client","Supabase JS v2","createServerClient for RSC, createBrowserClient for CSR"],
      ["Auth middleware","Supabase middleware.ts","refresh session on every request"],
      ["Payments","Stripe Node SDK","stripe.checkout.sessions.create"],
      ["Job queue","Trigger.dev v3","defineJob, cronTrigger per user"],
      ["PDF (SaaS)","reportlab or pdf-lib","fpdf2 not available in serverless JS"],
      ["Testing","Vitest + Playwright","unit + e2e"],
      ["CI","GitHub Actions","test on PR, deploy to Vercel on main"],
      ["Linting","ESLint + Prettier","airbnb config"],
    ]
  ),
  new Paragraph({ spacing: { after: 120 } }),
  h2("Key File Structure"),
  bullet("src/app/(auth)/login|register — auth pages"),
  bullet("src/app/(dashboard)/dashboard|lessons|settings|billing — protected routes"),
  bullet("src/app/admin — admin-only, middleware checks role claim"),
  bullet("src/app/api/auth|lessons|progress|subscription|preferences|admin|webhooks — route handlers"),
  bullet("src/lib/supabase/server.ts|client.ts — Supabase clients"),
  bullet("src/lib/gemini.ts — generateLesson(words, levels) -> WordData[]"),
  bullet("src/lib/pdf.ts — buildPdf(wordData, video, day, level) -> Buffer"),
  bullet("src/lib/email.ts — sendLesson(to, pdfBuffer, day, level) -> void"),
  bullet("src/lib/stripe.ts — createCheckout, createPortal, handleWebhook"),
  bullet("src/jobs/send-lesson.ts — Trigger.dev job definition"),
  bullet("src/jobs/schedule-user.ts — schedules/reschedules lesson cron per user"),
  bullet("supabase/migrations/ — all DB migrations with rollback scripts"),
];

// ── S7: Security & Compliance ─────────────────────────────────────────────────
const s7 = [
  h1("7. Security & Compliance"),
  tbl(["Area","Implementation"],
    [
      ["Auth tokens","JWT RS256, 1h access / 7d refresh, HttpOnly cookie for refresh"],
      ["API auth","Authorization: Bearer on all endpoints except /auth/* and /webhooks/stripe"],
      ["Row-level security","Supabase RLS: users can only read/write own rows"],
      ["Admin role","JWT claim role='admin', checked in middleware before /admin/* routes"],
      ["Stripe webhooks","Verify Stripe-Signature header with stripe.webhooks.constructEvent"],
      ["Password hashing","Supabase Auth handles bcrypt internally"],
      ["Rate limiting","Upstash Redis token bucket: 100 req/min free, 1000 pro, 10000 enterprise"],
      ["GDPR","DELETE /users/me hard-deletes all rows; GET /users/export returns full JSON"],
      ["Data retention","Supabase backups 30 days, R2 PDFs 1 year then auto-delete"],
      ["HTTPS","Enforced by Vercel, no HTTP downgrade"],
      ["Secrets","Vercel environment variables, never in code or logs"],
      ["Dependency scanning","Dependabot on GitHub, weekly scan"],
    ]
  ),
];

// ── S8: Launch Checklist ──────────────────────────────────────────────────────
const s8 = [
  h1("8. Launch Checklist"),
  h2("Pre-launch (week -2)"),
  tbl(["Task","Owner","Done?"],
    [
      ["Supabase project created, RLS enabled on all tables","Eng",""],
      ["Stripe account verified, products created (free/pro/enterprise)","Eng",""],
      ["Domain configured in Vercel, SSL active","Eng",""],
      ["SendGrid domain authenticated, DKIM/SPF records set","Eng",""],
      ["Trigger.dev workspace created, jobs registered","Eng",""],
      ["All environment variables set in Vercel","Eng",""],
      ["E2E test: register -> verify email -> day 1 lesson delivered","QA",""],
      ["Payment flow tested with Stripe test cards","QA",""],
      ["Admin panel: can view users, trigger send, override plan","QA",""],
      ["GDPR delete flow tested: all user data removed","QA",""],
      ["Status page live at status.deutschlernen.com","Eng",""],
      ["Privacy policy and Terms of Service pages live","Legal",""],
    ]
  ),
  new Paragraph({ spacing: { after: 120 } }),
  h2("Launch day"),
  tbl(["Task","Notes"],
    [
      ["Post on Product Hunt","Prepare: video, screenshots, tagline, first comment"],
      ["Post in r/German and r/languagelearning","Genuine post, no spam"],
      ["Tweet thread: what it is + how it works","Include GIF of lesson email"],
      ["Send to waitlist","Waitlist collected on landing page pre-launch"],
      ["Monitor Sentry for errors","First 4 hours: watch error rate"],
      ["Monitor SendGrid delivery rate","Target >99% delivered"],
    ]
  ),
];

// ── S9: Implementation Steps ──────────────────────────────────────────────────
const s9 = [
  h1("9. Implementation Steps"),
  tbl(["Phase","Task","Dependencies"],
    [
      ["1","Supabase setup: create tables, enable RLS, add migrations","None"],
      ["1","Next.js scaffold: app router, Tailwind, TypeScript strict","None"],
      ["1","Auth: Supabase Auth, register/login/verify pages + middleware","Supabase"],
      ["1","Dashboard page: progress ring + streak calendar (hardcoded mock data)","Auth"],
      ["2","Trigger.dev: define send-lesson job, schedule-user job","Supabase, Gemini key"],
      ["2","Gemini integration: port generateLesson() from Python main.py","None"],
      ["2","PDF generation: port pdf_builder.py to TypeScript with pdf-lib","None"],
      ["2","Email: SendGrid transactional email with PDF attachment","SendGrid account"],
      ["2","Lesson API routes: GET /lessons, GET /lessons/:day, POST /lessons/:day/resend","Supabase, jobs"],
      ["3","Stripe: products, checkout, portal, webhooks, subscription table updates","Stripe account"],
      ["3","Billing page: plan badge, upgrade CTA, invoice list","Stripe"],
      ["3","Paywall middleware: block /lessons beyond day 7 for free users","Stripe"],
      ["4","Admin panel: user table, metrics, queue view, plan override","All above"],
      ["4","Preferences page: timezone/time update triggers job reschedule","Trigger.dev"],
      ["4","Completion certificate: PDF generated on day 125, emailed + downloadable","PDF lib"],
      ["5","SEO: metadata, sitemap, blog scaffold, first 5 posts","None"],
      ["5","Monitoring: Sentry, Uptime Robot, status page","None"],
      ["5","Load test: simulate 1,000 concurrent lesson sends","Trigger.dev"],
    ]
  ),
];

// ── S10: Decisions & Non-obvious Choices ──────────────────────────────────────
const s10 = [
  h1("10. Key Decisions (Read This First)"),
  p("These are the non-obvious decisions already made. Do not revisit without strong reason."),
  tbl(["Decision","Choice","Reason"],
    [
      ["Word shuffle","random.Random(42) fixed seed on indices","Deterministic across runs; mixes categories across days"],
      ["Dedup strategy","3-layer: date guard + sequential index + explicit word set check","Defense in depth; hard exit(1) on overlap"],
      ["Gemini call","1 batched call for all 20 words","Avoids 20x API calls; Gemini handles large JSON output well"],
      ["Gemini retry","temp=0.7 first, then temp=0.0","Lower temp = more deterministic JSON on second attempt"],
      ["PDF font","Helvetica (fpdf2 core)","Latin-1 only; avoid Unicode encode errors for special chars"],
      ["Non-Latin chars","Replace bullet/en-dash/arrow with ASCII","fpdf2 Helvetica is Latin-1; no Unicode beyond 255"],
      ["JSON state files","Atomic write: .tmp + os.replace()","Prevents corrupt state on crash mid-write"],
      ["GitHub Actions cron","Dual: 0 6 and 0 5 UTC weekdays","Covers CET (UTC+1) and CEST (UTC+2); duplicate run rejected by date guard"],
      ["SaaS job queue","Trigger.dev (not cron)","Per-user timezone scheduling impossible with single cron"],
      ["SaaS PDF storage","Cloudflare R2 (not S3)","Cheaper egress; same S3-compatible API"],
      ["Word bank size","Exactly 500 A1 + 500 A2 + 1500 B1","Matches phase lengths: 25 days A1, 25 days A2, 75 days B1"],
      ["Email attachment","PDF in memory, attached inline","No temp file needed; cleaner serverless execution"],
      ["Git commit after send","Try/except, non-fatal","Email already sent; git failure should not re-trigger lesson"],
    ]
  ),
  new Paragraph({ spacing: { after: 120 } }),
  h2("Naming Conventions"),
  tbl(["Item","Convention","Example"],
    [
      ["Python files","snake_case","pdf_builder.py, email_sender.py"],
      ["TypeScript files","kebab-case","send-lesson.ts, schedule-user.ts"],
      ["DB tables","snake_case plural","users, lessons, word_cache"],
      ["API routes","kebab-case","/subscription/checkout, /lessons/:day/resend"],
      ["Env vars","SCREAMING_SNAKE","GEMINI_API_KEY, SENDER_APP_PASS"],
      ["Stripe products","Use metadata user_id","Always pass user_id in checkout metadata"],
      ["Trigger.dev jobs","kebab-case","send-daily-lesson, schedule-user-lesson"],
    ]
  ),
  new Paragraph({ spacing: { after: 120 } }),
  h2("Environment Variables Reference"),
  tbl(["Variable","Used In","Notes"],
    [
      ["GEMINI_API_KEY","main.py, src/lib/gemini.ts","aistudio.google.com free tier"],
      ["SENDER_EMAIL","email_sender.py","Gmail address"],
      ["SENDER_APP_PASS","email_sender.py","16-char app password, no spaces"],
      ["RECIPIENT_EMAIL","email_sender.py","Destination email"],
      ["NEXT_PUBLIC_SUPABASE_URL","SaaS frontend","Supabase project URL"],
      ["NEXT_PUBLIC_SUPABASE_ANON_KEY","SaaS frontend","Public anon key"],
      ["SUPABASE_SERVICE_ROLE_KEY","SaaS API routes","Never expose to client"],
      ["STRIPE_SECRET_KEY","SaaS API","sk_live_... or sk_test_..."],
      ["STRIPE_WEBHOOK_SECRET","SaaS webhooks","whsec_... from Stripe dashboard"],
      ["SENDGRID_API_KEY","SaaS email","SG.xxxxx"],
      ["TRIGGER_API_KEY","SaaS jobs","From Trigger.dev dashboard"],
      ["R2_ACCESS_KEY_ID","SaaS storage","Cloudflare R2 credentials"],
      ["R2_SECRET_ACCESS_KEY","SaaS storage",""],
      ["R2_BUCKET_NAME","SaaS storage","e.g. deutschtaeglich-pdfs"],
    ]
  ),
];

// ── S11: Test Run Workflow ────────────────────────────────────────────────────
const s11 = [
  h1("11. Test Run After Deploy (Non-Disruptive)"),
  p("After every git push, a test run fires immediately to verify the pipeline end-to-end. It must NOT consume a real day slot or affect tomorrow's schedule."),
  h2("How Test Run Works"),
  bullet("workflow_dispatch trigger fires automatically after push (via repository_dispatch or separate test workflow)"),
  bullet("Test run passes env var TEST_MODE=true to main.py"),
  bullet("In TEST_MODE: skip progress.json read/write, skip last_sent_words.json update, skip git commit"),
  bullet("Use fixed test word slice: SHUFFLED_WORDS[0:20] regardless of progress"),
  bullet("Send email to RECIPIENT_EMAIL with subject prefix [TEST] so it's identifiable"),
  bullet("Exit without modifying any state files"),
  h2("GitHub Actions Test Workflow"),
  tbl(["File","Path"],
    [["test_run.yml",".github/workflows/test_run.yml"]]
  ),
  bullet("Trigger: workflow_run (on completion of any push to main)"),
  bullet("Steps: checkout -> install deps -> python main.py with TEST_MODE=true"),
  bullet("Must complete within 5 minutes"),
  bullet("Does not block or delay the scheduled daily_german.yml workflow"),
  h2("main.py Test Mode Changes"),
  bullet("Read TEST_MODE = os.environ.get('TEST_MODE','') == 'true'"),
  bullet("If TEST_MODE: skip date guard, skip dedup check, use words[0:20], tag email '[TEST]', skip state writes, skip git commit"),
  bullet("Normal (non-test) run: unchanged behavior"),
];

// ── S12: Reference Data ───────────────────────────────────────────────────────
const PRO_TIPS_DATA = [
  [1,"Record yourself reading each word aloud — your brain encodes pronunciation far better when you hear your own voice."],
  [2,"Write each word on a sticky note and put it on the object it names — 'der Stuhl' on the chair, 'das Fenster' on the window."],
  [3,"Use the 'one sentence rule': never learn a word without also learning one sentence that uses it naturally."],
  [4,"German nouns are always capitalized — use this visual cue to spot and review nouns in any text you encounter."],
  [5,"Learn articles as part of the word from day one: it is 'der-Tisch' not just 'Tisch' — treat the article as inseparable."],
  [6,"Set your phone language to German for one full day — even if you change it back, you will have absorbed dozens of words."],
  [7,"Read the German Wikipedia article for one topic you already know well — familiarity removes guesswork and accelerates vocabulary."],
  [8,"Shadowing technique: play a German audio clip and speak along simultaneously — it trains mouth muscles and prosody together."],
  [9,"Use spaced repetition: review yesterday's 20 words briefly each morning before receiving today's lesson."],
  [10,"Find a German-speaking friend or italki tutor — even one 30-minute call per week multiplies retention dramatically."],
  [11,"Watch German films with German subtitles (not English) — your brain processes subtitles as reading practice, not as a crutch."],
  [12,"When you learn a verb, immediately learn its past tense form alongside it — 'kaufen / kaufte / gekauft'."],
  [13,"German compound nouns are made by joining smaller words — learn the components and you can decode new compounds on your own."],
  [14,"Read the news headlines on Deutsche Welle Langsam gesprochene Nachrichten (slowly spoken news) every morning."],
  [15,"Try the 'mental image' technique: for each new word, picture a vivid, ridiculous scene involving the word and an object you know."],
  [16,"Listen to the Easy German podcast during your commute — real street conversations build listening comprehension fast."],
  [17,"Write a 5-sentence German diary entry each evening using only today's words — even imperfect sentences build fluency."],
  [18,"Verbs with separable prefixes (auf-, an-, ab-) are common — always note whether a prefix is separable when you learn it."],
  [19,"Learn the top 20 German conjunctions this week — 'weil', 'obwohl', 'damit', 'sodass' — they transform sentences instantly."],
  [20,"Anki + this email is a powerful combo: add each day's 20 words to an Anki deck for SRS review alongside the rich content here."],
  [21,"German word order rule: time-manner-place (wann-wie-wo). 'Ich fahre morgen mit dem Zug nach Berlin.'"],
  [22,"The prefix 'un-' negates adjectives just like in English: 'gluecklich' (happy) -> 'ungluecklich' (unhappy)."],
  [23,"Learn 5 common German idioms this week — 'Ich druecke dir die Daumen' (I keep my fingers crossed) makes you sound native."],
  [24,"Read a German children's book — the grammar is correct, vocabulary is manageable, and illustrations provide context clues."],
  [25,"Celebrate completing A1 vocabulary! You now know the 500 most essential German words. Every word from here builds on this."],
  [26,"At A2, focus on connecting words: 'ausserdem', 'trotzdem', 'deswegen' — these words let you build real paragraphs."],
  [27,"Learn the German modal verbs perfectly this week: koennen, muessen, duerfen, sollen, wollen, moegen — they unlock everything."],
  [28,"German cases (Nominativ, Akkusativ, Dativ, Genitiv) change articles — make a small cheat-sheet card and keep it in your wallet."],
  [29,"The dative case is used after: mit, nach, seit, von, zu, bei, aus, gegenueber — memorize this list as a single chunk."],
  [30,"Watch German cooking videos on YouTube with the transcript open — food vocabulary sticks because it engages multiple senses."],
  [31,"Try 'thinking in German' during mundane tasks: describe what you are doing as you cook, walk, or clean, using today's words."],
  [32,"Learn the top 10 German irregular verbs this week (sein, haben, werden, gehen, kommen, sehen, geben, nehmen, stehen, fahren)."],
  [33,"German relative clauses send the verb to the end: 'Das Buch, das ich lese, ist interessant.' Practice this construction daily."],
  [34,"Podcasts at normal speed: 'Slow German mit Annik Rubens' uses simple vocabulary and clear pronunciation — ideal at A2 level."],
  [35,"Try a 'German-only day' once per week: no English for 24 hours. Use a dictionary for words you need, not a translator."],
  [36,"Learn how to tell time in German — 'Es ist Viertel nach drei' vs 'Es ist 15:15' — both forms are used and both must be known."],
  [37,"Build vocabulary around themes: write 10 words related to 'das Wetter' (weather) and construct a short weather description."],
  [38,"German has three genders but patterns exist: -ung, -heit, -keit are always feminine; -chen, -lein are always neuter."],
  [39,"Practice the Konjunktiv II (subjunctive) this week — 'koenntest du...', 'wuerde ich...' — essential for polite requests."],
  [40,"Read a simple German recipe and try to make the dish — following instructions in German is immersive and practical."],
  [41,"At this point you should be able to write a 10-sentence email in German. Write one to a language exchange partner today."],
  [42,"Learn 'false friends': 'bekommen' means 'to receive' (not 'to become'), 'also' means 'therefore' (not 'also'). These trip everyone up."],
  [43,"German has a rich diminutive system: 'Hund' -> 'Huendchen', 'Kind' -> 'Kindchen' — adding -chen or -lein makes things smaller/cuter."],
  [44,"Study the difference between 'seit' and 'vor': 'seit' = duration ongoing, 'vor' = ago. 'Seit zwei Jahren' vs 'Vor zwei Jahren'."],
  [45,"You have now learned 900 words! Try reading a Level A2 graded reader — short novels written for language learners."],
  [46,"Practice the perfect tense: most verbs use 'haben', but movement and state-change verbs use 'sein': 'Ich bin gegangen'."],
  [47,"German prepositions governing dative vs accusative: in/an/auf/ueber/unter/vor/hinter/neben/zwischen — learn which verbs trigger which case."],
  [48,"Watch the German film 'Das Leben der Anderen' with German subtitles — excellent B1-level language in every scene."],
  [49,"Learn the passive voice this week: 'Das Buch wird gelesen' (The book is being read). It appears constantly in formal writing."],
  [50,"Halfway to B1! Your vocabulary is now A2-complete. The next 75 days will transform your reading and listening comprehension."],
  [51,"At B1, start reading German newspapers: Zeit Online, Sueddeutsche Zeitung. Read just the headlines and first paragraph each day."],
  [52,"German has Futur I (werden + infinitiv) and Futur II (werden + Partizip II + sein/haben). Futur I is used even for present probability."],
  [53,"Learn academic connectors: 'einerseits...andererseits', 'zwar...aber', 'sowohl...als auch' — these appear in all formal German writing."],
  [54,"Try the TV series 'Dark' on Netflix in German with German subtitles — complex vocabulary but excellent immersion for motivated learners."],
  [55,"Practice Konjunktiv I (indirect speech): 'Er sagte, er sei muede' — essential for news reporting and academic writing in German."],
  [56,"Learn 10 German proverbs this week: 'Uebung macht den Meister' (Practice makes perfect) — proverbs encode cultural knowledge."],
  [57,"Study word formation: nouns from verbs (-ung: Hoffnung, Uebung), nouns from adjectives (-heit/-keit: Freiheit, Moeglichkeit)."],
  [58,"Read the German Wikipedia article on a city you want to visit — geography vocabulary combined with cultural knowledge."],
  [59,"At B1, you should understand about 70% of a German conversation. Watch a German talk show and count the words you miss."],
  [60,"Learn German business vocabulary this week — 'die Besprechung', 'der Termin', 'der Auftrag' — needed for professional contexts."],
  [61,"German humor often involves compound nouns: 'Verschlimmbessern' (making something worse while trying to improve it). Enjoy the creativity."],
  [62,"At day 62 you are officially past the halfway point. Your consistency has built a habit most people never manage. Keep going."],
  [63,"Learn the differences between 'denn', 'weil', and 'da' for expressing cause — they have subtle but important distinctions."],
  [64,"German has Modalpartikeln (modal particles) like 'doch', 'mal', 'ja', 'halt' — these are invisible to dictionaries but vital for tone."],
  [65,"Practice 'doch' — it refutes a negation: 'Du kommst nicht?' / 'Doch!' — no English equivalent; essential for natural German."],
  [66,"Study German prefix verbs systematically: 'stellen', 'hinstellen', 'aufstellen', 'vorstellen', 'darstellen' — each prefix shifts meaning."],
  [67,"Read a German short story collection — 'Kafkas Erzaehlungen' or modern authors like Daniel Kehlmann offer excellent B1+ input."],
  [68,"Try a German language app like Babbel or Busuu alongside this system — variety in input type accelerates acquisition."],
  [69,"At B1 you can have a conversation — join a German conversation group on Meetup or Tandem for weekly speaking practice."],
  [70,"Learn the Genitiv case this week: 'Das Auto meines Vaters' — often replaced by 'von' in speech but required in formal writing."],
  [71,"Study German punctuation rules: commas are mandatory before subordinate clauses ('Ich glaube, dass...') — this is not optional."],
  [72,"Watch German YouTube channels without subtitles for 10 minutes a day — even partial comprehension builds listening tolerance."],
  [73,"German emails have fixed formulas: 'Sehr geehrte/r...' to open, 'Mit freundlichen Gruessen' to close. Learn these conventions."],
  [74,"Learn 10 common German abbreviations: z.B. (zum Beispiel), d.h. (das heisst), usw. (und so weiter), etc. — they appear everywhere."],
  [75,"You have now studied for 75 days straight. That is extraordinary self-discipline. Three quarters complete. One month remains."],
  [76,"B1 grammar focus: 'um...zu' vs 'damit' for purpose clauses. 'Ich lerne Deutsch, um Arbeit zu finden' vs 'damit meine Kinder stolz sind'."],
  [77,"Study German number prefixes in words: 'mono-', 'bi-', 'tri-', 'quadro-' — they appear in technical and academic vocabulary frequently."],
  [78,"Practice expressing opinions: 'meiner Meinung nach', 'ich bin der Ansicht, dass', 'soweit ich weiss' — B1 exam essentials."],
  [79,"Learn conditional clauses: 'Wenn ich Zeit haette, wuerde ich Deutsch lernen' — Konjunktiv II in both clauses for unreal conditions."],
  [80,"Read a German job advertisement and write a one-paragraph cover letter (Bewerbungsanschreiben) — practical B1 writing exercise."],
  [81,"German has formal (Sie) and informal (du/ihr) address — when in doubt, always start formal and let the German speaker switch first."],
  [82,"Learn 'Redewendungen' (idioms) for emotions: 'jemandem auf den Wecker gehen' (to get on someone's nerves) — colorful and memorable."],
  [83,"At B1 you can decode most signs, menus, and instructions in Germany. Plan a virtual trip and read everything only in German."],
  [84,"Study verbs with fixed prepositions: 'warten auf', 'sich freuen ueber', 'denken an' — these cannot be translated literally."],
  [85,"Practice summary writing: read a German article and write 5 sentences summarizing it — this is the core B1 exam writing task."],
  [86,"German has many verbs of movement with direction: 'fahren' (general), 'fliegen' (fly), 'schwimmen' (swim) — direction words change meaning."],
  [87,"Learn the discourse markers used in German debates: 'zum einen', 'zum anderen', 'Hinzu kommt', 'Zusammenfassend laesst sich sagen'."],
  [88,"Study the German health vocabulary this week — doctor visits, pharmacies, insurance forms all require this vocabulary in Germany."],
  [89,"Read the B1 Goethe-Institut word list — it shows exactly what vocabulary is tested at B1 level. Compare it with what you have learned."],
  [90,"90 days in! You have built a rare skill. Most German learners quit before reaching B1. You are in the top 5% of starters."],
  [91,"At B1 you should understand German radio. Tune into Deutschlandfunk and listen for 10 minutes. How much do you catch?"],
  [92,"Study the 'Plusquamperfekt' (past perfect): 'Ich hatte gegessen, bevor er kam' — past before past. Needed for storytelling."],
  [93,"German scientific writing avoids passive using 'man': 'Man kann sagen' instead of 'Es kann gesagt werden' — both are correct."],
  [94,"Learn common German bureaucratic vocabulary — 'Anmeldung', 'Ummeldung', 'Behoerde', 'Formular' — daily life in Germany requires this."],
  [95,"Try a German tongue twister: 'Fischers Fritz fischt frische Fische' — it trains the ch/sch distinction that English speakers struggle with."],
  [96,"Study German diminutives with -chen and -lein: they always take 'das' regardless of the original gender — a useful shortcut."],
  [97,"Learn how Germans express time: 'in einer Stunde', 'vor einer Woche', 'seit Montag', 'bis naechsten Dienstag' — time expressions are foundational."],
  [98,"Practice telephone German: 'Einen Moment bitte', 'Koennte ich bitte mit... sprechen?', 'Ich rufe spaeter zurueck' — still needed for offices."],
  [99,"Write a short opinion essay in German (150 words) on any topic. Use connectors, examples, and a conclusion. Then check it with DeepL Write."],
  [100,"100 days! You have been consistent for 100 weekdays. Your vocabulary of 2,000 words puts you firmly in the B1 range. Remarkable."],
  [101,"In the last 25 days: focus on consolidation. Try to use words in context more than studying new vocabulary rules."],
  [102,"Listen to a German audiobook of a book you have already read in English — prior knowledge of the plot eliminates comprehension bottleneck."],
  [103,"Study 'Nominalisierungen' (nominalization of verbs): 'entwickeln' -> 'die Entwicklung' — common in academic and news writing."],
  [104,"Learn the top 20 German collocations: words that always appear together: 'eine Entscheidung treffen', 'Fortschritte machen', 'Kontakt aufnehmen'."],
  [105,"Read a German Wikipedia article on history and identify the past tenses used — you will see Praeteritum (simple past) dominating written narrative."],
  [106,"Study verb-noun collocations: 'einen Vertrag abschliessen', 'eine Frage stellen', 'Verantwortung uebernehmen' — these are tested at B1 level."],
  [107,"Practice translating your thoughts directly: pick an English sentence and immediately say it in German without writing it down first."],
  [108,"German has two past tenses: Praeteritum (written/formal) and Perfekt (spoken) — use Perfekt in conversation, Praeteritum in writing."],
  [109,"Learn the top 10 German transition words for essays: 'jedoch', 'dennoch', 'nichtsdestoweniger', 'darueber hinaus', 'im Gegensatz dazu'."],
  [110,"At this level you can read most German websites. Navigate a German government website (bund.de) and complete a simulated task."],
  [111,"German has Zwillingsformeln (twin formulas): 'schwarz-weiss', 'Schritt fuer Schritt', 'hier und da' — fixed pairs that always appear together."],
  [112,"Study the vocabulary for expressing uncertainty: 'vermutlich', 'moeglicherweise', 'es koennte sein, dass', 'soweit mir bekannt ist'."],
  [113,"At B1 you can talk about abstract topics. Practice: describe your opinion on climate change or technology using 10 sentences in German."],
  [114,"Learn how to write a formal complaint in German — 'Sehr geehrte Damen und Herren, hiermit moechte ich Folgendes mitteilen...' — practical and testable."],
  [115,"Review all 125 pro tips from day 1 through today. Which advice did you not follow? Now is the time to implement the missing pieces."],
  [116,"Write a 200-word German text on any topic without looking anything up. Then review it. This is your B1 writing benchmark."],
  [117,"Listen to a full German podcast episode without subtitles. Write 5 sentences summarizing what you understood. Comprehension at scale."],
  [118,"German register matters: 'du' with friends, 'Sie' with officials, formal vocabulary in writing, informal in speech. Master the switch."],
  [119,"Study German idioms using body parts: 'jemandem auf die Nerven gehen', 'ein Auge zudruecken', 'Augen auf!' — vivid and memorable."],
  [120,"At 2,400 words, your passive vocabulary allows reading of most non-specialist German texts. Start reading a German novel this week."],
  [121,"Five days left. These final 100 words are advanced B1 vocabulary that will take you to the doorstep of B2. Savor each one."],
  [122,"Write a letter to yourself in German — describe where you started, how far you have come, and what you plan to do with your German."],
  [123,"Take a practice B1 exam: Goethe-Institut offers sample papers at goethe.de. Your vocabulary preparation for the exam is now complete."],
  [124,"Tomorrow is your last day. You have 2,480 words. You can read, write, listen, and speak in German. Tell someone what you have done."],
  [125,"Day 125. You did it. 2,500 German words. A1 to B1 in exactly 125 weekdays. Now book a B1 exam or a trip to Germany. You are ready."],
];

const s12 = [
  h1("12. Reference Data"),
  h2("12.1 All 125 Pro Tips"),
  p("These tips are embedded in pdf_builder.py as PRO_TIPS list. Day N gets PRO_TIPS[N-1]."),
  tbl(["Day","Pro Tip"], PRO_TIPS_DATA.map(([day, tip]) => [String(day), tip])),
];

// ── S13: Word Bank Sample & Grammar Reference ────────────────────────────────
const WORD_SAMPLE_A1 = [
  ["der Abend","evening","A1"],["die Adresse","address","A1"],["alt","old","A1"],
  ["anfangen","to start","A1"],["anrufen","to call","A1"],["die Antwort","answer","A1"],
  ["die Arbeit","work","A1"],["arbeiten","to work","A1"],["der Arzt","doctor (m)","A1"],
  ["auch","also","A1"],["auf","on / up","A1"],["aufstehen","to get up","A1"],
  ["das Auto","car","A1"],["die Bahn","train / rail","A1"],["bald","soon","A1"],
  ["der Bahnhof","train station","A1"],["beginnen","to begin","A1"],["bei","at / near","A1"],
  ["das Bett","bed","A1"],["bezahlen","to pay","A1"],["billig","cheap","A1"],
  ["bitte","please","A1"],["brauchen","to need","A1"],["der Brief","letter","A1"],
  ["das Brot","bread","A1"],["der Bruder","brother","A1"],["das Buch","book","A1"],
  ["der Bus","bus","A1"],["da","there / since","A1"],["danke","thank you","A1"],
  ["das","the (neuter)","A1"],["denken","to think","A1"],["der","the (masc)","A1"],
  ["deutsch","German","A1"],["die","the (fem/pl)","A1"],["Dienstag","Tuesday","A1"],
  ["Donnerstag","Thursday","A1"],["dort","there","A1"],["durch","through","A1"],
  ["dürfen","may / to be allowed","A1"],["ein","a / an","A1"],["einladen","to invite","A1"],
  ["einkaufen","to shop","A1"],["das Essen","food / meal","A1"],["essen","to eat","A1"],
  ["fahren","to drive / travel","A1"],["die Familie","family","A1"],["finden","to find","A1"],
  ["Freitag","Friday","A1"],["die Frau","woman / wife","A1"],["fragen","to ask","A1"],
  ["früh","early","A1"],["gehen","to go","A1"],["das Geld","money","A1"],
  ["gern","gladly / to like","A1"],["groß","big","A1"],["gut","good","A1"],
  ["haben","to have","A1"],["halb","half","A1"],["das Haus","house","A1"],
  ["helfen","to help","A1"],["heute","today","A1"],["hier","here","A1"],
  ["hören","to listen / hear","A1"],["das Hotel","hotel","A1"],["ich","I","A1"],
  ["immer","always","A1"],["das Jahr","year","A1"],["jetzt","now","A1"],
  ["kaufen","to buy","A1"],["kein","no / not a","A1"],["das Kind","child","A1"],
  ["klein","small","A1"],["kommen","to come","A1"],["können","can / to be able","A1"],
  ["kosten","to cost","A1"],["die Küche","kitchen","A1"],["kurz","short","A1"],
  ["das Land","country / land","A1"],["lang","long","A1"],["lernen","to learn","A1"],
  ["lesen","to read","A1"],["die Leute","people","A1"],["lieber","preferably","A1"],
  ["machen","to make / do","A1"],["der Mann","man / husband","A1"],["die Mutter","mother","A1"],
  ["nach","after / to","A1"],["die Nacht","night","A1"],["der Name","name","A1"],
  ["nehmen","to take","A1"],["neu","new","A1"],["nicht","not","A1"],
  ["nichts","nothing","A1"],["noch","still / yet","A1"],["Montag","Monday","A1"],
];

const WORD_SAMPLE_A2 = [
  ["der Alltag","everyday life","A2"],["allein","alone","A2"],["anbieten","to offer","A2"],
  ["die Ausbildung","training / apprenticeship","A2"],["außerdem","besides / moreover","A2"],
  ["die Bedeutung","meaning / importance","A2"],["benutzen","to use","A2"],
  ["der Beruf","profession / job","A2"],["beschreiben","to describe","A2"],
  ["bestellen","to order","A2"],["besuchen","to visit","A2"],["bieten","to offer","A2"],
  ["bleiben","to stay","A2"],["der Bürger","citizen","A2"],["die Chance","chance / opportunity","A2"],
  ["daher","therefore","A2"],["damals","back then","A2"],["damit","so that / with it","A2"],
  ["dauern","to last / take time","A2"],["doch","but / however / yes (contradiction)","A2"],
  ["dringend","urgent","A2"],["einfach","simple / simply","A2"],["einige","some / a few","A2"],
  ["die Einladung","invitation","A2"],["entscheiden","to decide","A2"],
  ["die Entscheidung","decision","A2"],["entwickeln","to develop","A2"],
  ["die Entwicklung","development","A2"],["erklären","to explain","A2"],
  ["die Erklärung","explanation","A2"],["erlauben","to allow","A2"],
  ["erreichen","to reach / achieve","A2"],["erzählen","to tell / narrate","A2"],
  ["die Erfahrung","experience","A2"],["erwarten","to expect","A2"],
  ["das Ereignis","event","A2"],["erinnern","to remember","A2"],
  ["die Erinnerung","memory / reminder","A2"],["fallen","to fall","A2"],
  ["fast","almost","A2"],["fertig","ready / finished","A2"],["folgen","to follow","A2"],
  ["die Frage","question","A2"],["freundlich","friendly","A2"],
  ["die Freundschaft","friendship","A2"],["früher","earlier / formerly","A2"],
  ["führen","to lead","A2"],["fühlen","to feel","A2"],["geben","to give","A2"],
  ["die Gegend","area / region","A2"],["die Gelegenheit","opportunity","A2"],
  ["das Gespräch","conversation","A2"],["gestern","yesterday","A2"],
  ["glauben","to believe","A2"],["gleichzeitig","simultaneously","A2"],
  ["hängen","to hang","A2"],["die Hauptstadt","capital city","A2"],
  ["halten","to hold / stop","A2"],["häufig","frequent / often","A2"],
  ["die Herausforderung","challenge","A2"],["der Hinweis","hint / note","A2"],
  ["hingegen","on the other hand","A2"],["höflich","polite","A2"],
  ["immer noch","still","A2"],["informieren","to inform","A2"],
  ["die Information","information","A2"],["die Interesse","interest","A2"],
  ["je","each / the more... the more","A2"],["die Jugend","youth","A2"],
  ["kaufen","to buy","A2"],["kaum","barely / hardly","A2"],
  ["die Kommunikation","communication","A2"],["die Kosten","costs","A2"],
  ["der Kunde","customer (m)","A2"],["laufen","to run / walk","A2"],
  ["leider","unfortunately","A2"],["lösen","to solve","A2"],
  ["die Lösung","solution","A2"],["meinen","to mean / think","A2"],
  ["die Meinung","opinion","A2"],["der Mensch","person / human","A2"],
  ["merken","to notice","A2"],["die Möglichkeit","possibility","A2"],
  ["möglich","possible","A2"],["nämlich","namely / because","A2"],
  ["natürlich","of course / naturally","A2"],["nerven","to annoy","A2"],
  ["nutzen","to use","A2"],["nützlich","useful","A2"],
  ["offen","open","A2"],["öffentlich","public","A2"],
];

const WORD_SAMPLE_B1 = [
  ["abgeben","to hand in / submit","B1"],["abhängen von","to depend on","B1"],
  ["absichtlich","intentional","B1"],["die Abteilung","department","B1"],
  ["abwechslungsreich","varied","B1"],["die Ahnung","idea / clue","B1"],
  ["aktuell","current","B1"],["die Analyse","analysis","B1"],
  ["analysieren","to analyze","B1"],["die Anforderung","requirement","B1"],
  ["angemessen","appropriate","B1"],["die Annahme","assumption","B1"],
  ["annehmen","to assume / accept","B1"],["der Antrag","application / motion","B1"],
  ["aufgrund","due to / because of","B1"],["aufmerksam","attentive","B1"],
  ["die Aufmerksamkeit","attention","B1"],["ausführlich","detailed","B1"],
  ["ausgerechnet","of all people/things","B1"],["ausnahmsweise","for once / exceptionally","B1"],
  ["die Auswirkung","impact / effect","B1"],["beachten","to pay attention to","B1"],
  ["beantragen","to apply for","B1"],["der Begriff","concept / term","B1"],
  ["beinhalten","to contain / include","B1"],["bekannt","known / famous","B1"],
  ["die Bemühung","effort","B1"],["bemerken","to notice","B1"],
  ["die Benachteiligung","disadvantage","B1"],["der Bereich","area / field","B1"],
  ["berücksichtigen","to take into account","B1"],["der Beschluss","decision / resolution","B1"],
  ["beschränken","to limit","B1"],["die Besonderheit","special feature","B1"],
  ["bestehen aus","to consist of","B1"],["betonen","to emphasize","B1"],
  ["die Beziehung","relationship","B1"],["beziehen sich auf","to refer to","B1"],
  ["bisher","so far / up to now","B1"],["bürokratisch","bureaucratic","B1"],
  ["die Darstellung","presentation / depiction","B1"],["darstellen","to represent","B1"],
  ["demnach","therefore / accordingly","B1"],["demokratisch","democratic","B1"],
  ["der Druck","pressure","B1"],["durchführen","to carry out","B1"],
  ["effektiv","effective","B1"],["eigenartig","peculiar / strange","B1"],
  ["einschließlich","including","B1"],["die Einschränkung","restriction","B1"],
  ["die Einstellung","attitude / setting","B1"],["einwandern","to immigrate","B1"],
  ["die Entschuldigung","apology / excuse","B1"],["entsprechen","to correspond to","B1"],
  ["die Entsprechung","equivalent","B1"],["entstehen","to emerge / develop","B1"],
  ["das Ergebnis","result","B1"],["erhöhen","to increase","B1"],
  ["ermöglichen","to enable","B1"],["erneut","again / anew","B1"],
  ["die Erscheinung","appearance / phenomenon","B1"],["ersetzen","to replace","B1"],
  ["erweitern","to expand","B1"],["die Fähigkeit","ability / skill","B1"],
  ["die Folge","consequence / episode","B1"],["die Förderung","support / funding","B1"],
  ["fordern","to demand","B1"],["fördern","to support / promote","B1"],
  ["die Freiheit","freedom","B1"],["die Führung","leadership","B1"],
  ["die Gemeinschaft","community","B1"],["gerecht","fair / just","B1"],
  ["die Gerechtigkeit","justice","B1"],["die Gesellschaft","society","B1"],
  ["die Gesundheit","health","B1"],["die Gewalt","violence / force","B1"],
  ["gleichmäßig","even / uniform","B1"],["globalisierung","globalization","B1"],
  ["die Grenze","border / limit","B1"],["die Grundlage","basis / foundation","B1"],
  ["grundsätzlich","fundamental / in principle","B1"],["handeln","to act / deal","B1"],
  ["häufig","frequent","B1"],["der Haushalt","household / budget","B1"],
];

const s13 = [
  h1("13. Word Bank Reference Sample"),
  p("Samples from the 2,500-word bank used by word_bank.py. Full word bank is in the codebase. These samples illustrate the vocabulary scope at each level."),
  h2("13.1 A1 Level Sample (First 96 of 500 words)"),
  tbl(["German Word","English Meaning","Level"], WORD_SAMPLE_A1.map(([g,e,l])=>[g,e,l])),
  new Paragraph({ spacing: { after: 120 } }),
  h2("13.2 A2 Level Sample (First 96 of 500 words)"),
  tbl(["German Word","English Meaning","Level"], WORD_SAMPLE_A2.map(([g,e,l])=>[g,e,l])),
  new Paragraph({ spacing: { after: 120 } }),
  h2("13.3 B1 Level Sample (First 80 of 1500 words)"),
  tbl(["German Word","English Meaning","Level"], WORD_SAMPLE_B1.map(([g,e,l])=>[g,e,l])),
  new Paragraph({ spacing: { after: 120 } }),
  h2("13.4 Grammar Reference: Article Table"),
  tbl(["Case","Masculine (der)","Feminine (die)","Neuter (das)","Plural (die)"],
    [
      ["Nominativ","der","die","das","die"],
      ["Akkusativ","den","die","das","die"],
      ["Dativ","dem","der","dem","den"],
      ["Genitiv","des","der","des","der"],
    ]
  ),
  new Paragraph({ spacing: { after: 120 } }),
  h2("13.5 Grammar Reference: Indefinite Article"),
  tbl(["Case","Masculine (ein)","Feminine (eine)","Neuter (ein)"],
    [
      ["Nominativ","ein","eine","ein"],
      ["Akkusativ","einen","eine","ein"],
      ["Dativ","einem","einer","einem"],
      ["Genitiv","eines","einer","eines"],
    ]
  ),
  new Paragraph({ spacing: { after: 120 } }),
  h2("13.6 Essential German Phrases by Situation"),
  tbl(["Situation","German Phrase","English Meaning"],
    [
      ["Greeting","Guten Morgen!","Good morning!"],
      ["Greeting","Guten Tag!","Good day / Hello!"],
      ["Greeting","Guten Abend!","Good evening!"],
      ["Greeting","Hallo!","Hello! (informal)"],
      ["Greeting","Wie geht es Ihnen?","How are you? (formal)"],
      ["Greeting","Wie geht's?","How's it going? (informal)"],
      ["Farewell","Auf Wiedersehen!","Goodbye! (formal)"],
      ["Farewell","Tschüss!","Bye! (informal)"],
      ["Farewell","Bis bald!","See you soon!"],
      ["Farewell","Bis morgen!","See you tomorrow!"],
      ["Politeness","Bitte","Please / You're welcome"],
      ["Politeness","Danke schön!","Thank you very much!"],
      ["Politeness","Entschuldigung!","Excuse me! / Sorry!"],
      ["Politeness","Es tut mir leid.","I'm sorry."],
      ["Politeness","Kein Problem!","No problem!"],
      ["Politeness","Gern geschehen!","You're welcome! (gladly done)"],
      ["Introduction","Ich heiße...","My name is..."],
      ["Introduction","Ich komme aus...","I come from..."],
      ["Introduction","Ich bin... Jahre alt.","I am ... years old."],
      ["Introduction","Freut mich!","Nice to meet you!"],
      ["Introduction","Darf ich mich vorstellen?","May I introduce myself?"],
      ["Shopping","Was kostet das?","How much does that cost?"],
      ["Shopping","Haben Sie das in einer anderen Größe?","Do you have that in a different size?"],
      ["Shopping","Ich hätte gerne...","I would like..."],
      ["Shopping","Wo ist die Kasse?","Where is the cash register?"],
      ["Shopping","Kann ich mit Karte zahlen?","Can I pay by card?"],
      ["Shopping","Das ist zu teuer.","That is too expensive."],
      ["Restaurant","Einen Tisch für zwei, bitte.","A table for two, please."],
      ["Restaurant","Die Speisekarte, bitte.","The menu, please."],
      ["Restaurant","Ich möchte bestellen.","I would like to order."],
      ["Restaurant","Was empfehlen Sie?","What do you recommend?"],
      ["Restaurant","Die Rechnung, bitte!","The bill, please!"],
      ["Restaurant","Es hat sehr gut geschmeckt.","It tasted very good."],
      ["Transport","Wo ist der Bahnhof?","Where is the train station?"],
      ["Transport","Wann fährt der nächste Zug?","When does the next train leave?"],
      ["Transport","Eine Fahrkarte nach..., bitte.","One ticket to..., please."],
      ["Transport","Auf welchem Gleis?","On which platform?"],
      ["Transport","Ich habe mich verfahren.","I got lost (driving)."],
      ["Transport","Wie weit ist es?","How far is it?"],
      ["Health","Ich bin krank.","I am sick."],
      ["Health","Ich habe Kopfschmerzen.","I have a headache."],
      ["Health","Ich brauche einen Arzt.","I need a doctor."],
      ["Health","Wo ist die nächste Apotheke?","Where is the nearest pharmacy?"],
      ["Health","Rufen Sie einen Krankenwagen!","Call an ambulance!"],
      ["Health","Ich bin allergisch gegen...","I am allergic to..."],
      ["Work","Wo arbeiten Sie?","Where do you work?"],
      ["Work","Was machen Sie beruflich?","What do you do for work?"],
      ["Work","Ich bin... von Beruf.","I am a ... by profession."],
      ["Work","Ich suche eine Stelle.","I am looking for a job."],
      ["Work","Ich habe eine Frage.","I have a question."],
      ["Work","Können Sie das wiederholen?","Can you repeat that?"],
      ["Communication","Sprechen Sie Deutsch?","Do you speak German?"],
      ["Communication","Ich spreche kein Deutsch.","I don't speak German."],
      ["Communication","Können Sie langsamer sprechen?","Can you speak more slowly?"],
      ["Communication","Wie bitte?","Pardon? / What did you say?"],
      ["Communication","Ich verstehe nicht.","I don't understand."],
      ["Communication","Was bedeutet das?","What does that mean?"],
      ["Communication","Wie schreibt man das?","How do you write / spell that?"],
      ["Time","Wie spät ist es?","What time is it?"],
      ["Time","Es ist halb drei.","It is half past two."],
      ["Time","Viertel nach vier.","Quarter past four."],
      ["Time","Viertel vor fünf.","Quarter to five."],
      ["Time","morgen früh","tomorrow morning"],
      ["Time","übermorgen","the day after tomorrow"],
      ["Time","vorgestern","the day before yesterday"],
      ["Weather","Wie ist das Wetter heute?","What is the weather like today?"],
      ["Weather","Es regnet.","It is raining."],
      ["Weather","Es schneit.","It is snowing."],
      ["Weather","Es ist sonnig.","It is sunny."],
      ["Weather","Es ist kalt / warm / heiß.","It is cold / warm / hot."],
      ["Weather","Der Wind weht stark.","The wind is blowing strongly."],
    ]
  ),
  new Paragraph({ spacing: { after: 120 } }),
  h2("13.7 Common German Prefixes and Their Meanings"),
  tbl(["Prefix","Meaning","Example (German)","Example (English)"],
    [
      ["un-","negation / opposite","unglücklich","unhappy"],
      ["ver-","away / change / wrongly","verlieren","to lose"],
      ["be-","to make / applies action","benutzen","to use"],
      ["er-","result / achieving","erreichen","to achieve"],
      ["ent-","removal / beginning","entscheiden","to decide"],
      ["ge-","past participle marker","gemacht","made"],
      ["miss-","wrong / bad","missverstehen","to misunderstand"],
      ["über-","over / too much","übertreiben","to exaggerate"],
      ["unter-","under / below","untersuchen","to examine"],
      ["aus-","out / outward","ausgehen","to go out"],
      ["auf-","up / open","aufmachen","to open"],
      ["an-","at / toward / on","ankommen","to arrive"],
      ["ab-","away / down / off","abfahren","to depart"],
      ["ein-","in / into","einladen","to invite"],
      ["vor-","before / pre-","vorstellen","to introduce"],
      ["nach-","after / following","nachfragen","to enquire"],
      ["mit-","with / together","mitbringen","to bring along"],
      ["zurück-","back / return","zurückkommen","to come back"],
      ["weiter-","further / continue","weitermachen","to continue"],
      ["durch-","through / complete","durchführen","to carry out"],
      ["um-","around / re-","umsteigen","to transfer / change"],
      ["los-","start / loose","losgehen","to set off"],
      ["fest-","firm / hold","festhalten","to hold on"],
      ["vor-","forward / ahead","vorwärtskommen","to make progress"],
      ["voll-","full / complete","vollenden","to complete"],
    ]
  ),
  new Paragraph({ spacing: { after: 120 } }),
  h2("13.8 German Suffixes for Word Formation"),
  tbl(["Suffix","Creates","Gender","Example","Meaning"],
    [
      ["-ung","noun from verb","die (f)","Hoffnung","hope"],
      ["-heit","noun from adj","die (f)","Freiheit","freedom"],
      ["-keit","noun from adj","die (f)","Möglichkeit","possibility"],
      ["-schaft","collective noun","die (f)","Freundschaft","friendship"],
      ["-tion","-tion nouns","die (f)","Information","information"],
      ["-ität","-ity nouns","die (f)","Qualität","quality"],
      ["-ismus","-ism nouns","der (m)","Tourismus","tourism"],
      ["-ist","person / agent","der (m)","Tourist","tourist"],
      ["-er","agent / person","der (m)","Arbeiter","worker"],
      ["-ler","agent / person","der (m)","Sportler","athlete"],
      ["-chen","diminutive","das (n)","Mädchen","girl / little maid"],
      ["-lein","diminutive","das (n)","Büchlein","little book"],
      ["-nis","result noun","das (n)","Ergebnis","result"],
      ["-tum","state / domain","das (n)","Eigentum","property"],
      ["-lich","adjective from noun","—","freundlich","friendly"],
      ["-ig","adjective from noun","—","sonnig","sunny"],
      ["-isch","adjective / origin","—","typisch","typical"],
      ["-bar","able to be...","—","tragbar","portable"],
      ["-sam","inclined to...","—","langsam","slow"],
      ["-los","without / -less","—","arbeitslos","unemployed"],
      ["-voll","full of...","—","liebevoll","loving"],
    ]
  ),
  new Paragraph({ spacing: { after: 120 } }),
  h2("13.9 Numbers Reference"),
  tbl(["Number","German","Number","German"],
    [
      ["0","null","20","zwanzig"],
      ["1","eins","21","einundzwanzig"],
      ["2","zwei","30","dreißig"],
      ["3","drei","40","vierzig"],
      ["4","vier","50","fünfzig"],
      ["5","fünf","60","sechzig"],
      ["6","sechs","70","siebzig"],
      ["7","sieben","80","achtzig"],
      ["8","acht","90","neunzig"],
      ["9","neun","100","hundert"],
      ["10","zehn","200","zweihundert"],
      ["11","elf","1,000","tausend"],
      ["12","zwölf","1,000,000","eine Million"],
      ["13","dreizehn","1st","erste(r/s)"],
      ["14","vierzehn","2nd","zweite(r/s)"],
      ["15","fünfzehn","3rd","dritte(r/s)"],
      ["16","sechzehn","4th","vierte(r/s)"],
      ["17","siebzehn","10th","zehnte(r/s)"],
      ["18","achtzehn","20th","zwanzigste(r/s)"],
      ["19","neunzehn","100th","hundertste(r/s)"],
    ]
  ),
  new Paragraph({ spacing: { after: 120 } }),
  h2("13.10 Full 125-Day Schedule Reference"),
  p("Each row shows day number, word index range (0-based, from SHUFFLED_WORDS), CEFR level, and cumulative words sent. Use this to verify progress.json alignment."),
  tbl(["Day","Word Start","Word End","Level","Cumulative"],
    Array.from({length:125},(_,i)=>{
      const day=i+1, start=i*20, end=start+20;
      const level = day<=25?"A1":day<=50?"A2":"B1";
      return [String(day),String(start),String(end),level,String(end)];
    })
  ),
  new Paragraph({ spacing: { after: 120 } }),
  h2("13.11 Separable Verbs Reference"),
  tbl(["Verb (infinitive)","Prefix","Base","Present (ich)","Meaning"],
    [
      ["anfangen","an-","fangen","fange an","to start"],
      ["anrufen","an-","rufen","rufe an","to call (phone)"],
      ["anziehen","an-","ziehen","ziehe an","to put on (clothes)"],
      ["aufhören","auf-","hören","höre auf","to stop"],
      ["aufmachen","auf-","machen","mache auf","to open"],
      ["aufräumen","auf-","räumen","räume auf","to tidy up"],
      ["aufstehen","auf-","stehen","stehe auf","to get up"],
      ["ausgehen","aus-","gehen","gehe aus","to go out"],
      ["ausziehen","aus-","ziehen","ziehe aus","to take off / move out"],
      ["einladen","ein-","laden","lade ein","to invite"],
      ["einkaufen","ein-","kaufen","kaufe ein","to go shopping"],
      ["einschlafen","ein-","schlafen","schlafe ein","to fall asleep"],
      ["fernsehen","fern-","sehen","sehe fern","to watch TV"],
      ["hereinkommen","herein-","kommen","komme herein","to come in"],
      ["mitkommen","mit-","kommen","komme mit","to come along"],
      ["mitnehmen","mit-","nehmen","nehme mit","to take along"],
      ["nachfragen","nach-","fragen","frage nach","to follow up / enquire"],
      ["vorbereiten","vor-","bereiten","bereite vor","to prepare"],
      ["vorstellen","vor-","stellen","stelle vor","to introduce"],
      ["wegfahren","weg-","fahren","fahre weg","to drive away"],
      ["weggehen","weg-","gehen","gehe weg","to go away"],
      ["weitermachen","weiter-","machen","mache weiter","to continue"],
      ["zuhören","zu-","hören","höre zu","to listen"],
      ["zumachen","zu-","machen","mache zu","to close"],
      ["zurückkommen","zurück-","kommen","komme zurück","to come back"],
      ["zurückgehen","zurück-","gehen","gehe zurück","to go back"],
      ["zusammenarbeiten","zusammen-","arbeiten","arbeite zusammen","to work together"],
      ["abfahren","ab-","fahren","fahre ab","to depart"],
      ["abholen","ab-","holen","hole ab","to pick up"],
      ["absagen","ab-","sagen","sage ab","to cancel"],
    ]
  ),
  new Paragraph({ spacing: { after: 120 } }),
  h2("13.12 Grammar Reference: Common Irregular Verbs"),
  tbl(["Verb","Meaning","Present (ich)","Simple Past","Past Participle"],
    [
      ["sein","to be","bin","war","gewesen"],
      ["haben","to have","habe","hatte","gehabt"],
      ["werden","to become","werde","wurde","geworden"],
      ["können","can","kann","konnte","gekonnt"],
      ["müssen","must","muss","musste","gemusst"],
      ["dürfen","may","darf","durfte","gedurft"],
      ["wollen","to want","will","wollte","gewollt"],
      ["sollen","should","soll","sollte","gesollt"],
      ["mögen","to like","mag","mochte","gemocht"],
      ["gehen","to go","gehe","ging","gegangen"],
      ["kommen","to come","komme","kam","gekommen"],
      ["sehen","to see","sehe","sah","gesehen"],
      ["geben","to give","gebe","gab","gegeben"],
      ["nehmen","to take","nehme","nahm","genommen"],
      ["fahren","to drive","fahre","fuhr","gefahren"],
      ["lassen","to let","lasse","ließ","gelassen"],
      ["stehen","to stand","stehe","stand","gestanden"],
      ["halten","to hold","halte","hielt","gehalten"],
      ["denken","to think","denke","dachte","gedacht"],
      ["bringen","to bring","bringe","brachte","gebracht"],
      ["wissen","to know","weiß","wusste","gewusst"],
      ["finden","to find","finde","fand","gefunden"],
      ["liegen","to lie (down)","liege","lag","gelegen"],
      ["schreiben","to write","schreibe","schrieb","geschrieben"],
      ["lesen","to read","lese","las","gelesen"],
      ["sprechen","to speak","spreche","sprach","gesprochen"],
    ]
  ),
];

const doc = new Document({
  creator: "Duggirala German Daily System",
  title: "DeutschTaeglich SaaS Roadmap",
  description: "Concise technical reference for Claude Code",
  sections: [{
    properties: {
      page: {
        size: { width: PAGE_W, height: PAGE_H },
        margin: { top: MARGIN, right: MARGIN, bottom: MARGIN, left: MARGIN },
      },
    },
    children: [
      ...cover,
      new Paragraph({ pageBreakBefore: true }),
      ...s1,
      new Paragraph({ pageBreakBefore: true }),
      ...s2,
      new Paragraph({ pageBreakBefore: true }),
      ...s3,
      new Paragraph({ pageBreakBefore: true }),
      ...s4,
      new Paragraph({ pageBreakBefore: true }),
      ...s5,
      new Paragraph({ pageBreakBefore: true }),
      ...s6,
      new Paragraph({ pageBreakBefore: true }),
      ...s7,
      new Paragraph({ pageBreakBefore: true }),
      ...s8,
      new Paragraph({ pageBreakBefore: true }),
      ...s9,
      new Paragraph({ pageBreakBefore: true }),
      ...s10,
      new Paragraph({ pageBreakBefore: true }),
      ...s11,
      new Paragraph({ pageBreakBefore: true }),
      ...s12,
      new Paragraph({ pageBreakBefore: true }),
      ...s13,
    ],
  }],
});

Packer.toBuffer(doc).then(buffer => {
  fs.writeFileSync("SAAS_ROADMAP.docx", buffer);
  console.log(`SAAS_ROADMAP.docx written: ${buffer.length} bytes`);
});
