# ─────────────────────────────────────────
# Duggirala
# German Daily Learning System
# ─────────────────────────────────────────

# DW "Nicos Weg" — official Deutsche Welle German-learning series.
# Verified via YouTube oEmbed API. A1: 76 eps, A2: 76 eps, B1: 76 eps.
# Videos are matched to the day's CEFR level in main.py.

VIDEOS_A1 = [
    "https://www.youtube.com/watch?v=dC6ZGLzdaTs",   # A1 Folge 01: Hallo!
    "https://www.youtube.com/watch?v=upvuC9FR-xU",   # A1 Folge 02: Kein Problem!
    "https://www.youtube.com/watch?v=idFrq0H1Af0",   # A1 Folge 03: Tschüss!
    "https://www.youtube.com/watch?v=-qAuGimugds",   # A1 Folge 04: Von A bis Z
    "https://www.youtube.com/watch?v=FoYSUfsLcjA",   # A1 Folge 05: Ich heiße Emma
    "https://www.youtube.com/watch?v=fZr-eVZ3YOs",   # A1 Folge 06: Das ist Nico
    "https://www.youtube.com/watch?v=Q7ECRAQrzFc",   # A1 Folge 07: Woher kommst du
    "https://www.youtube.com/watch?v=T89sIATrpBc",   # A1 Folge 08: Nico hat ein Problem
    "https://www.youtube.com/watch?v=p1dci7nBJRo",   # A1 Folge 09: Zahlen von 1 bis 100
    "https://www.youtube.com/watch?v=5wyalwdmpzk",   # A1 Folge 10: Wichtige Nummern
    "https://www.youtube.com/watch?v=AI9EmNzxXGE",   # A1 Folge 11: Adressen
    "https://www.youtube.com/watch?v=IhLqeX8QjSg",   # A1 Folge 12: Auf dem Amt
    "https://www.youtube.com/watch?v=VWDtpIIAgAI",   # A1 Folge 13: Was machst du hier
    "https://www.youtube.com/watch?v=J71RxF7qU2o",   # A1 Folge 14: Was trinkst du
    "https://www.youtube.com/watch?v=w-Zea1mverM",   # A1 Folge 15: Zwei Tee, bitte!
    "https://www.youtube.com/watch?v=c7LTbMCKVNo",   # A1 Folge 16: Zahlen, bitte!
    "https://www.youtube.com/watch?v=IQ3cDBISOao",   # A1 Folge 17: Ich war schon in Berlin
    "https://www.youtube.com/watch?v=3K991pj4Uic",   # A1 Folge 18: Wo liegt das
    "https://www.youtube.com/watch?v=uJ6uLjJxX-8",   # A1 Folge 19: In Europa
    "https://www.youtube.com/watch?v=lvgs_iLBdvY",   # A1 Folge 20: Andere Länder
    "https://www.youtube.com/watch?v=9obS6QT10To",   # A1 Folge 21: Was ist das
    "https://www.youtube.com/watch?v=MNx10ASRCwM",   # A1 Folge 22: Wem gehört das
    "https://www.youtube.com/watch?v=P1ontBJYzhI",   # A1 Folge 23: Ich habe kein …
    "https://www.youtube.com/watch?v=368pARWAzGk",   # A1 Folge 24: Das Auto ist rot
    "https://www.youtube.com/watch?v=bbZxpdieqIA",   # A1 Folge 25: So wohne ich
    "https://www.youtube.com/watch?v=YRWehEtSPQY",   # A1 Folge 26: Meine Wohnung
    "https://www.youtube.com/watch?v=s9y2sCNOzBk",   # A1 Folge 27: Sofa, Sessel und Tisch
    "https://www.youtube.com/watch?v=Q-qjyb9AsqM",   # A1 Folge 28: Unser Haus
    "https://www.youtube.com/watch?v=AGwxwx3TOdg",   # A1 Folge 29: Emmas Tag
    "https://www.youtube.com/watch?v=jUElkIpQlNw",   # A1 Folge 30: Tageszeiten
    "https://www.youtube.com/watch?v=f9kkMWEOxo0",   # A1 Folge 31: Am Sonntag koche ich
    "https://www.youtube.com/watch?v=dqtdmvpa8D0",   # A1 Folge 32: Emmas Wochenende
    "https://www.youtube.com/watch?v=SEV3kmyQCII",   # A1 Folge 33: Wie spät ist es
    "https://www.youtube.com/watch?v=Vvt6H_EvGX0",   # A1 Folge 34: Hast du morgen Zeit
    "https://www.youtube.com/watch?v=_VUrkdITl8U",   # A1 Folge 35: Wann spielen wir
    "https://www.youtube.com/watch?v=2v6H7fnWuts",   # A1 Folge 36: Zu spät!
    "https://www.youtube.com/watch?v=rH8HMCr73RM",   # A1 Folge 37: Ich bin Lehrerin
    "https://www.youtube.com/watch?v=a7LZ0QAG6DQ",   # A1 Folge 38: Mein Beruf
    "https://www.youtube.com/watch?v=ymE5ZON70C0",   # A1 Folge 39: Wo ist der Aufzug
    "https://www.youtube.com/watch?v=qaQd9wFy1l4",   # A1 Folge 40: Traumberuf
    "https://www.youtube.com/watch?v=Fz_AuTNFa8k",   # A1 Folge 41: Wo ist der Bahnhof
    "https://www.youtube.com/watch?v=5_pXp3akjr4",   # A1 Folge 42: An der Ampel links
    "https://www.youtube.com/watch?v=4us1ZoH9K04",   # A1 Folge 43: Mit Bus und Bahn
    "https://www.youtube.com/watch?v=dsPDJb2956A",   # A1 Folge 44: Im Büro
    "https://www.youtube.com/watch?v=3tq7bRB9iu0",   # A1 Folge 45: Lebensmittel
    "https://www.youtube.com/watch?v=sEu2PqmGrgw",   # A1 Folge 46: Ich mag (nicht)!
    "https://www.youtube.com/watch?v=SIN9PejV-OI",   # A1 Folge 47: Haushaltsarbeit
    "https://www.youtube.com/watch?v=KeU3-5jr2fI",   # A1 Folge 48: Was macht dir Spaß
    "https://www.youtube.com/watch?v=ySrfaSqtdfw",   # A1 Folge 49: Mengen und Preise
    "https://www.youtube.com/watch?v=dOdHXwy0cME",   # A1 Folge 50: Was darf es sein
    "https://www.youtube.com/watch?v=SRAk_KZlrwY",   # A1 Folge 51: Sonst noch etwas
    "https://www.youtube.com/watch?v=0S3urnio_08",   # A1 Folge 52: Wie viel Mehl
    "https://www.youtube.com/watch?v=3UJeXeiki9g",   # A1 Folge 53: Wie war dein Urlaub
    "https://www.youtube.com/watch?v=b4ki5lMyd4Q",   # A1 Folge 54: Jahreszeiten
    "https://www.youtube.com/watch?v=chmqnserFqM",   # A1 Folge 55: Der Ausflug
    "https://www.youtube.com/watch?v=qL1hgrjJScY",   # A1 Folge 56: Wie wird das Wetter
    "https://www.youtube.com/watch?v=DiNQle2s1lQ",   # A1 Folge 57: Das ist jetzt modern
    "https://www.youtube.com/watch?v=9iJnx2PESSk",   # A1 Folge 58: Mein Lieblingspulli
    "https://www.youtube.com/watch?v=pCRS-oxE61k",   # A1 Folge 59: Das passt gut!
    "https://www.youtube.com/watch?v=eYaoCcvPd_U",   # A1 Folge 60: Schick!
    "https://www.youtube.com/watch?v=6CQ32OWDyq4",   # A1 Folge 61: Meine Familie
    "https://www.youtube.com/watch?v=KJ-icYRJ29s",   # A1 Folge 62: Meine Eltern
    "https://www.youtube.com/watch?v=4U9iAmC3rFQ",   # A1 Folge 63: Meine Tante
    "https://www.youtube.com/watch?v=oJmH9eD7Lao",   # A1 Folge 64: Mein Bruder
    "https://www.youtube.com/watch?v=otY2T26FOP0",   # A1 Folge 65: Von Kopf bis Fuß
    "https://www.youtube.com/watch?v=B7MMM3SrSlg",   # A1 Folge 66: Bist du fit
    "https://www.youtube.com/watch?v=826-EwY51Fw",   # A1 Folge 67: Fitness
    "https://www.youtube.com/watch?v=DiMQTg7D7Ao",   # A1 Folge 68: Ist das gesund
    "https://www.youtube.com/watch?v=0b66BzvKgMY",   # A1 Folge 69: Geht es dir gut
    "https://www.youtube.com/watch?v=cTJ1KFzmhbc",   # A1 Folge 70: Beim Arzt
    "https://www.youtube.com/watch?v=ilp0CwKxdbY",   # A1 Folge 71: Gute Besserung!
    "https://www.youtube.com/watch?v=VWomWeeqsAk",   # A1 Folge 72: Nehmen Sie …
    "https://www.youtube.com/watch?v=mkXWqvL3-hA",   # A1 Folge 73: Meine Heimat
    "https://www.youtube.com/watch?v=ppIFbtiL1kQ",   # A1 Folge 74: Leben in Deutschland
    "https://www.youtube.com/watch?v=k8_8CA5Ls94",   # A1 Folge 75: Anders als zu Hause
    "https://www.youtube.com/watch?v=bgnox1SRrw8",   # A1 Folge 76: Ich träume von …
]

VIDEOS_A2 = [
    "https://www.youtube.com/watch?v=ZPQepR4B8eo",   # A2 Folge 01: Lebenslinien
    "https://www.youtube.com/watch?v=WB4YmgiRULw",   # A2 Folge 02: Angekommen
    "https://www.youtube.com/watch?v=A1k6ZjKFycM",   # A2 Folge 03: Pläne machen
    "https://www.youtube.com/watch?v=J7j31w8UT2c",   # A2 Folge 04: Sprichst du Deutsch
    "https://www.youtube.com/watch?v=dRga5jIMjBo",   # A2 Folge 05: Geld ist für mich …
    "https://www.youtube.com/watch?v=geYuMJBnDSs",   # A2 Folge 06: Mein Bankkonto
    "https://www.youtube.com/watch?v=tNY9TNnQC6E",   # A2 Folge 07: Rechnungen
    "https://www.youtube.com/watch?v=n_l-rfcG5Uo",   # A2 Folge 08: Am Bankautomaten
    "https://www.youtube.com/watch?v=uOcZq9rS13Y",   # A2 Folge 09: Familiengeschichten
    "https://www.youtube.com/watch?v=Tor-mPRS3j4",   # A2 Folge 10: Personen beschreiben
    "https://www.youtube.com/watch?v=Xw7Kv0o5a1Y",   # A2 Folge 11: Generationen
    "https://www.youtube.com/watch?v=MUcfiKAJUGg",   # A2 Folge 12: Alten- und Pflegeheim
    "https://www.youtube.com/watch?v=JmjnyhFLXKg",   # A2 Folge 13: Wohngemeinschaft
    "https://www.youtube.com/watch?v=i4IJP4s14k8",   # A2 Folge 14: Nachbarschaft
    "https://www.youtube.com/watch?v=sOaWFjMkDpg",   # A2 Folge 15: Kinder
    "https://www.youtube.com/watch?v=Qrso_HEyc1Q",   # A2 Folge 16: Anders als ihr
    "https://www.youtube.com/watch?v=rTgkeG4IJJw",   # A2 Folge 17: Unterwegs
    "https://www.youtube.com/watch?v=0ijgOLUE3NQ",   # A2 Folge 18: Im Hotel
    "https://www.youtube.com/watch?v=iU7swr8-hk0",   # A2 Folge 19: Bahnreisen
    "https://www.youtube.com/watch?v=qqxSuoX0gzw",   # A2 Folge 20: Der Ticketautomat
    "https://www.youtube.com/watch?v=oEWakpD2JaQ",   # A2 Folge 21: Alltag und Freizeit
    "https://www.youtube.com/watch?v=8e_ukBPtxww",   # A2 Folge 22: Freizeitstress
    "https://www.youtube.com/watch?v=PrrbATyrg08",   # A2 Folge 23: Das hört sich gut an!
    "https://www.youtube.com/watch?v=29d2dcAU_yc",   # A2 Folge 24: Das meinen Sie nicht ernst!
    "https://www.youtube.com/watch?v=8tgE0aw2Z1s",   # A2 Folge 25: Das macht mir Spaß!
    "https://www.youtube.com/watch?v=Nvm2oVmhAQQ",   # A2 Folge 26: Im Verein
    "https://www.youtube.com/watch?v=IIKgD8vCV6M",   # A2 Folge 27: Das macht mir Sorgen!
    "https://www.youtube.com/watch?v=10T22TlEO4k",   # A2 Folge 28: Das ist mir wichtig!
    "https://www.youtube.com/watch?v=YMUUh71lMb0",   # A2 Folge 29: Immer und überall
    "https://www.youtube.com/watch?v=xuVnMMMztx0",   # A2 Folge 30: Das Internet
    "https://www.youtube.com/watch?v=CRga4lKBmKI",   # A2 Folge 31: Mit freundlichen Grüßen
    "https://www.youtube.com/watch?v=aGW9URYStCA",   # A2 Folge 32: Reklamation
    "https://www.youtube.com/watch?v=gCkFdPgl6Qw",   # A2 Folge 33: Essen gehen
    "https://www.youtube.com/watch?v=G9QmyF9kswg",   # A2 Folge 34: Die Karte, bitte!
    "https://www.youtube.com/watch?v=0AcRBW-jZd8",   # A2 Folge 35: Was darf es sein
    "https://www.youtube.com/watch?v=W0VbXqKsVwU",   # A2 Folge 36: Ich bin Koch
    "https://www.youtube.com/watch?v=wkYF5wSzpl8",   # A2 Folge 37: Bei uns oder bei euch
    "https://www.youtube.com/watch?v=DZJugzCaF_E",   # A2 Folge 38: Ich bin neu hier
    "https://www.youtube.com/watch?v=g0G3sZLdp2Q",   # A2 Folge 39: Mein Traumpartner
    "https://www.youtube.com/watch?v=UBEciL_HRD8",   # A2 Folge 40: Alte und neue Freunde
    "https://www.youtube.com/watch?v=rtmGEfOu8NM",   # A2 Folge 41: Stadt oder Land
    "https://www.youtube.com/watch?v=5Qu4i1syMyg",   # A2 Folge 42: Auf Wohnungssuche
    "https://www.youtube.com/watch?v=vjAr8ESS224",   # A2 Folge 43: Der Umzug
    "https://www.youtube.com/watch?v=UIRE7AzCqW4",   # A2 Folge 44: Unfälle im Haushalt
    "https://www.youtube.com/watch?v=RDO_hbD3x80",   # A2 Folge 45: Das Leben heute und damals
    "https://www.youtube.com/watch?v=yxmxVrCApYs",   # A2 Folge 46: Alles anders
    "https://www.youtube.com/watch?v=06xS4_FL3rw",   # A2 Folge 47: Frauensache
    "https://www.youtube.com/watch?v=67zwrRg1ojs",   # A2 Folge 48: Damals
    "https://www.youtube.com/watch?v=ykG8dVplZ_g",   # A2 Folge 49: Berufswahl
    "https://www.youtube.com/watch?v=LVJE6bNAQIk",   # A2 Folge 50: Bewerbung
    "https://www.youtube.com/watch?v=906tHgfvtm0",   # A2 Folge 51: Ist die Stelle noch frei
    "https://www.youtube.com/watch?v=Dhql0UqC_7U",   # A2 Folge 52: Bewerbungsgespräch
    "https://www.youtube.com/watch?v=_SDkhbcFNEY",   # A2 Folge 53: Kulturkalender
    "https://www.youtube.com/watch?v=T3CrZNcK51w",   # A2 Folge 54: Eine Stadtbesichtigung
    "https://www.youtube.com/watch?v=kzZYziMty98",   # A2 Folge 55: Ein Bürger dieser Stadt
    "https://www.youtube.com/watch?v=eyA-znUsG6s",   # A2 Folge 56: Theater und Konzerte
    "https://www.youtube.com/watch?v=3E5-72iBE-g",   # A2 Folge 57: Feste und Feiertage
    "https://www.youtube.com/watch?v=qSJVQ_fDU1o",   # A2 Folge 58: Ein Jahr - viele Feste
    "https://www.youtube.com/watch?v=ucwxX2lkbVM",   # A2 Folge 59: Was passiert, wenn …
    "https://www.youtube.com/watch?v=8kxxx2A0EEQ",   # A2 Folge 60: So feiern wir!
    "https://www.youtube.com/watch?v=f2H3Nn06sZw",   # A2 Folge 61: Herzlichen Glückwunsch!
    "https://www.youtube.com/watch?v=c4BwgMDwhZY",   # A2 Folge 62: Passende Geschenke
    "https://www.youtube.com/watch?v=F840iqGLzac",   # A2 Folge 63: Was sollen wir schenken
    "https://www.youtube.com/watch?v=de2Vc6ApuCk",   # A2 Folge 64: Lieblingsfeste
    "https://www.youtube.com/watch?v=5hpf2kSCgrU",   # A2 Folge 65: Ein Praktikum beim Film
    "https://www.youtube.com/watch?v=ybXqenCs6IA",   # A2 Folge 66: Der Film war toll!
    "https://www.youtube.com/watch?v=YbLe0_MGKWs",   # A2 Folge 67: Im Filmstudio
    "https://www.youtube.com/watch?v=Y5BG4HPbqQ0",   # A2 Folge 68: Ich bin Schauspieler
    "https://www.youtube.com/watch?v=P4peOpNWFMo",   # A2 Folge 69: Einfach Super!
    "https://www.youtube.com/watch?v=-5QYdfCxoIk",   # A2 Folge 70: Das regt mich auf!
    "https://www.youtube.com/watch?v=bgn5Vaxc_dw",   # A2 Folge 71: Meiner Meinung nach
    "https://www.youtube.com/watch?v=_AQEm1Q_HYU",   # A2 Folge 72: Ich bin Fußballfan
    "https://www.youtube.com/watch?v=j5HdQlf-ZgQ",   # A2 Folge 73: Praktisch!
    "https://www.youtube.com/watch?v=lVJxT8KoVew",   # A2 Folge 74: Das funktioniert so!
    "https://www.youtube.com/watch?v=fSR4Jip04G4",   # A2 Folge 75: Das brauche ich!
    "https://www.youtube.com/watch?v=wml6VnrgPcc",   # A2 Folge 76: Wer hat's erfunden
]

VIDEOS_B1 = [
    "https://www.youtube.com/watch?v=o1zJ-BNQrU0",   # B1 Folge 01: Berufsberatung
    "https://www.youtube.com/watch?v=GwhGWqlGUUY",   # B1 Folge 02: Meine Muttersprache
    "https://www.youtube.com/watch?v=2itTid0YMtw",   # B1 Folge 03: Bei der Arbeit
    "https://www.youtube.com/watch?v=du_3kNU5Fkc",   # B1 Folge 04: Zukunftspläne
    "https://www.youtube.com/watch?v=EZo4Eja_36Y",   # B1 Folge 05: Zu wenig Zeit
    "https://www.youtube.com/watch?v=6qM8fggEPLs",   # B1 Folge 06: Keine Zeit
    "https://www.youtube.com/watch?v=NbGHxrQXqyI",   # B1 Folge 07: Pünktlichkeit
    "https://www.youtube.com/watch?v=M4x5Xy94aoc",   # B1 Folge 08: Jetzt oder nie
    "https://www.youtube.com/watch?v=0FiFNWpFVYc",   # B1 Folge 09: Heimat
    "https://www.youtube.com/watch?v=Gf-CF34SJJU",   # B1 Folge 10: Krieg und Frieden
    "https://www.youtube.com/watch?v=3P7t_K9vH4g",   # B1 Folge 11: Die Mauer
    "https://www.youtube.com/watch?v=oKCWlrpecbM",   # B1 Folge 12: Wiedervereinigung
    "https://www.youtube.com/watch?v=Kc4CQUxZnd8",   # B1 Folge 13: Alltagsprobleme
    "https://www.youtube.com/watch?v=FL0n-FMuxhA",   # B1 Folge 14: Geldprobleme
    "https://www.youtube.com/watch?v=ninxzogj1a0",   # B1 Folge 15: Tipps und Ratschläge
    "https://www.youtube.com/watch?v=SaS8pVzOw4o",   # B1 Folge 16: Alle haben Probleme
    "https://www.youtube.com/watch?v=DGAUVpI0UEc",   # B1 Folge 17: Jobsuche
    "https://www.youtube.com/watch?v=D3QhN29ElDM",   # B1 Folge 18: Stellenanzeigen
    "https://www.youtube.com/watch?v=K04r60Qn8Xg",   # B1 Folge 19: Eine Bewerbung schreiben
    "https://www.youtube.com/watch?v=EpJ_41Luj70",   # B1 Folge 20: Der erste Eindruck
    "https://www.youtube.com/watch?v=8S0mn_aNzF8",   # B1 Folge 21: Typisch
    "https://www.youtube.com/watch?v=1fx2xwU4q_8",   # B1 Folge 22: Anders!
    "https://www.youtube.com/watch?v=B_QwrJ942rM",   # B1 Folge 23: Jobs und Gender
    "https://www.youtube.com/watch?v=-OqXfyc5IjE",   # B1 Folge 24: Rollenverteilung
    "https://www.youtube.com/watch?v=zem97zeG2Wg",   # B1 Folge 25: Partnersuche
    "https://www.youtube.com/watch?v=mhZN7rjapNg",   # B1 Folge 26: Partnerschaft
    "https://www.youtube.com/watch?v=GXB2AP7g5Tw",   # B1 Folge 27: Männer und Frauen
    "https://www.youtube.com/watch?v=V6l97kuzCC4",   # B1 Folge 28: Beziehungsprobleme
    "https://www.youtube.com/watch?v=AuIzibbM_70",   # B1 Folge 29: Mein Arbeitsplatz
    "https://www.youtube.com/watch?v=Cbj4jP5OYUc",   # B1 Folge 30: Mein Gehalt
    "https://www.youtube.com/watch?v=ckeiIwN7hsc",   # B1 Folge 31: 112
    "https://www.youtube.com/watch?v=Qfu8gkskjiI",   # B1 Folge 32: Gut versichert
    "https://www.youtube.com/watch?v=VQUA15tTF44",   # B1 Folge 33: Schule
    "https://www.youtube.com/watch?v=6L9T0ws9G4A",   # B1 Folge 34: Schulalltag
    "https://www.youtube.com/watch?v=mcRkGyix6W0",   # B1 Folge 35: Lernen
    "https://www.youtube.com/watch?v=8cl5TcErxx4",   # B1 Folge 36: Berufe an der Schule
    "https://www.youtube.com/watch?v=UPzXoIkaQgw",   # B1 Folge 37: Die Berufswahl
    "https://www.youtube.com/watch?v=GrSMlUJr5q4",   # B1 Folge 38: Weiterbildung
    "https://www.youtube.com/watch?v=VX_uSzM3iiU",   # B1 Folge 39: Praktikum
    "https://www.youtube.com/watch?v=WnEdvr4j-S4",   # B1 Folge 40: Studium und Beruf
    "https://www.youtube.com/watch?v=4C5ZSPgm8_Y",   # B1 Folge 41: Wetter und Klima
    "https://www.youtube.com/watch?v=8lvi4ikm2dI",   # B1 Folge 42: Wieder so ein Wetter
    "https://www.youtube.com/watch?v=VQZjfGpBV1k",   # B1 Folge 43: Wegen des Wetters
    "https://www.youtube.com/watch?v=5RTopgCxnog",   # B1 Folge 44: Es wird wärmer
    "https://www.youtube.com/watch?v=9UvFx5xYYi4",   # B1 Folge 45: Mensch und Umwelt
    "https://www.youtube.com/watch?v=EXMSLSGn9U0",   # B1 Folge 46: Umweltbelastungen
    "https://www.youtube.com/watch?v=RvkSvNngJ7U",   # B1 Folge 47: Umweltschutz
    "https://www.youtube.com/watch?v=jvESl1J1a3s",   # B1 Folge 48: Wertstoffe
    "https://www.youtube.com/watch?v=iZnvAYAkgTk",   # B1 Folge 49: In der Zeitung steht
    "https://www.youtube.com/watch?v=EYhY1coVIn8",   # B1 Folge 50: In der Redaktion
    "https://www.youtube.com/watch?v=hjAsFLhtHsg",   # B1 Folge 51: Analog oder digital
    "https://www.youtube.com/watch?v=AnSwRq-Y9Ys",   # B1 Folge 52: Kontaktanzeigen
    "https://www.youtube.com/watch?v=gire8Lrd6gI",   # B1 Folge 53: Peinlich!
    "https://www.youtube.com/watch?v=-9h-NgKEDII",   # B1 Folge 54: Richtiges Benehmen
    "https://www.youtube.com/watch?v=k1wv5qVy2NY",   # B1 Folge 55: Benimmregeln
    "https://www.youtube.com/watch?v=9UGG6LqVw94",   # B1 Folge 56: Was tun, wenn …
    "https://www.youtube.com/watch?v=dB-WPrGP--s",   # B1 Folge 57: Endlich erwachsen
    "https://www.youtube.com/watch?v=0yvY1H3i4Ss",   # B1 Folge 58: Was Eltern erwarten
    "https://www.youtube.com/watch?v=CjDcCMIw980",   # B1 Folge 59: Lebenswege
    "https://www.youtube.com/watch?v=yET2vvqJrs0",   # B1 Folge 60: Noch mal anfangen
    "https://www.youtube.com/watch?v=F4Uqilxa58A",   # B1 Folge 61: Bund und Länder
    "https://www.youtube.com/watch?v=DMi5V4tnYZo",   # B1 Folge 62: Die EU
    "https://www.youtube.com/watch?v=KscLevVv_4I",   # B1 Folge 63: Gerechtigkeit
    "https://www.youtube.com/watch?v=zIZ2QKPgQv0",   # B1 Folge 64: Wir haben die Wahl
    "https://www.youtube.com/watch?v=0ITiIdOYDU4",   # B1 Folge 65: Das Ruhrgebiet
    "https://www.youtube.com/watch?v=qvW3utaRE7I",   # B1 Folge 66: Industrie
    "https://www.youtube.com/watch?v=TapQKTeaobs",   # B1 Folge 67: Strukturwandel
    "https://www.youtube.com/watch?v=H1XVv8kdgm4",   # B1 Folge 68: Kultur
    "https://www.youtube.com/watch?v=gj-iShcGNtc",   # B1 Folge 69: Nach Deutschland
    "https://www.youtube.com/watch?v=YKnX6XtOxqg",   # B1 Folge 70: Migrationsgründe
    "https://www.youtube.com/watch?v=nztA-DbTelQ",   # B1 Folge 71: Hin und zurück
    "https://www.youtube.com/watch?v=cMDwQDTdpSU",   # B1 Folge 72: Existenzgründung
    "https://www.youtube.com/watch?v=B0B2Lpte73E",   # B1 Folge 73: Neue Heimat
    "https://www.youtube.com/watch?v=Aw11bcQZki8",   # B1 Folge 74: So geht's!
    "https://www.youtube.com/watch?v=1zTF46mpEMQ",   # B1 Folge 75: Zukunftspläne
    "https://www.youtube.com/watch?v=IQXLae2MNiw",   # B1 Folge 76: Wünsche und Träume
]

# Flat list kept for backward compatibility (tests check len==228 total but we use per-level)
VIDEOS = VIDEOS_A1 + VIDEOS_A2 + VIDEOS_B1

VIDEOS_BY_LEVEL = {
    "A1": VIDEOS_A1,
    "A2": VIDEOS_A2,
    "B1": VIDEOS_B1,
}
